import { Tour } from '@/types'

export const TOURS: Tour[] = [
  {
    id: '1',
    name: 'Blue Hole',
    slug: 'blue-hole',
    description: 'Swim, jump and explore the iconic Blue Hole in St. Ann. Surrounded by lush tropical forest, this natural swimming hole is one of Jamaica\'s hidden gems. Enjoy cliff jumping, rope swings, and crystal-clear fresh water.',
    duration: '3-4 Hours',
    price: 85,
    category: 'day_tour',
    images: [
      '/images/tours/blue-hole.jpg',
      '/images/tours/dunns-river.jpg',
      '/images/tours/custom-tours.jpg',
    ],
    highlights: [
      'Guided nature walk through tropical forest',
      'Cliff jumping and rope swings',
      'Natural fresh water swimming',
      'Stunning waterfall scenery',
      'Local guide with safety briefing',
      'Refreshments included',
    ],
    available: true,
  },
  {
    id: '2',
    name: "Wabba's Weed Adventure",
    slug: 'wabbas-weed-adventure',
    description: 'An exciting river adventure on the Martha Brae River. Float through lush jungle terrain on bamboo rafts guided by expert local rafters. Experience the magic of Jamaica\'s river culture.',
    duration: '2-3 Hours',
    price: 65,
    category: 'day_tour',
    images: [
      '/images/tours/wabbas-adventure.jpg',
      '/images/tours/blue-hole.jpg',
      '/images/tours/custom-tours.jpg',
    ],
    highlights: [
      'Bamboo raft river tour',
      'Expert local rafter guide',
      'Scenic jungle waterway',
      'Wildlife sightings',
      'Photo opportunities throughout',
      'Authentic Jamaican river experience',
    ],
    available: true,
  },
  {
    id: '3',
    name: "Dunn's River Falls",
    slug: 'dunns-river-falls',
    description: "Climb the world-famous Dunn's River Falls in Ocho Rios. This iconic terraced waterfall stretches over 600 feet and is one of Jamaica's most popular attractions. A guided group climb makes it safe and fun for all fitness levels.",
    duration: '3-5 Hours',
    price: 75,
    category: 'day_tour',
    images: [
      '/images/tours/dunns-river.jpg',
      '/images/tours/wabbas-adventure.jpg',
      '/images/tours/blue-hole.jpg',
    ],
    highlights: [
      'Guided waterfall climb',
      'Over 600 feet of terraced falls',
      'Beach access at base',
      'Professional photography available',
      'Gift shops and dining nearby',
      'Suitable for all fitness levels',
    ],
    available: true,
  },
  {
    id: '8',
    name: 'Mayfield Falls',
    slug: 'mayfield-falls',
    description: 'Wade through the cool, tumbling pools of Mayfield Falls in the Westmoreland hills. A guided river walk past waterfalls and swimming holes surrounded by untouched rainforest.',
    duration: '3-4 Hours',
    price: 75,
    category: 'day_tour',
    images: ['/images/tours/mayfield-falls.jpg'], // representative stock photo, not verified as this exact location — swap when real photo available
    highlights: [
      'Guided river walk through the falls',
      'Multiple natural swimming pools',
      'Untouched rainforest scenery',
      'Local guide with safety briefing',
      'Comfortable air-conditioned vehicle',
      'Flexible pickup times',
    ],
    available: true,
  },
  {
    id: '9',
    name: 'Y.S. Falls',
    slug: 'ys-falls',
    description: "Ride the jitney into the property and swim beneath Y.S. Falls' seven cascading tiers in St. Elizabeth. Rope swings, a river tube ride, and picnic grounds make it a full day of fun.",
    duration: '3-4 Hours',
    price: 70,
    category: 'day_tour',
    images: ['/images/tours/ys-falls.jpg'], // representative stock photo, not verified as this exact location — swap when real photo available
    highlights: [
      'Jitney ride to the falls',
      'Seven-tiered waterfall swimming',
      'Rope swing and river tube ride',
      'Picnic grounds on-site',
      'Comfortable air-conditioned vehicle',
      'Flexible pickup times',
    ],
    available: true,
  },
  {
    id: '10',
    name: 'Black River Safari Tour',
    slug: 'black-river-safari-tour',
    description: "Cruise Jamaica's longest river by boat through mangrove wetlands, spotting crocodiles, birdlife, and lush scenery on this guided Black River safari in St. Elizabeth.",
    duration: '2-3 Hours',
    price: 65,
    category: 'day_tour',
    images: ['/images/tours/black-river-safari.jpg'],
    highlights: [
      'Guided boat safari on Black River',
      'Crocodile and birdlife sightings',
      'Mangrove wetland scenery',
      'Knowledgeable local boat captain',
      'Comfortable air-conditioned vehicle',
      'Flexible pickup times',
    ],
    available: true,
  },
  {
    id: '11',
    name: 'Benta River',
    slug: 'benta-river',
    description: 'Escape to the Benta River for a peaceful day of swimming and tubing in clear, calm waters surrounded by quiet countryside — a laid-back alternative to the busier river spots.',
    duration: '2-3 Hours',
    price: 60,
    category: 'day_tour',
    images: ['/images/tours/benta-river.jpg'], // representative stock photo, not verified as this exact location — swap when real photo available
    highlights: [
      'Swimming in calm river water',
      'Tubing option available',
      'Quiet, less crowded setting',
      'Local guide with recommendations',
      'Comfortable air-conditioned vehicle',
      'Flexible pickup times',
    ],
    available: true,
  },
  {
    id: '12',
    name: "Rick's Cafe",
    slug: 'ricks-cafe',
    description: "Watch cliff divers leap into the sea and catch a legendary Negril sunset at Rick's Cafe, perched on the West End cliffs — one of Jamaica's most iconic sunset spots.",
    duration: '2-3 Hours',
    price: 50,
    category: 'day_tour',
    images: ['/images/tours/ricks-cafe.jpg'],
    highlights: [
      'Cliff jumping and diving shows',
      'West End cliffside setting',
      'Legendary Negril sunset views',
      'Local guide with recommendations',
      'Comfortable air-conditioned vehicle',
      'Flexible pickup times',
    ],
    available: true,
  },
  {
    id: '13',
    name: '7 Miles Beach (Negril)',
    slug: 'seven-mile-beach-negril',
    description: "Relax on the powder-white sands of Negril's famous Seven Mile Beach, with calm turquoise water perfect for swimming, water sports, and beachside dining.",
    duration: 'Half Day',
    price: 45,
    category: 'day_tour',
    images: ['/images/tours/seven-mile-beach.jpg'],
    highlights: [
      'White sand beach access',
      'Calm, swimmable turquoise water',
      'Water sports available',
      'Beachside dining nearby',
      'Comfortable air-conditioned vehicle',
      'Flexible pickup times',
    ],
    available: true,
  },
  {
    id: '14',
    name: 'Pelican Bar',
    slug: 'pelican-bar',
    description: 'Take a boat ride out to the Pelican Bar, a rustic wooden bar built on a sandbar in the middle of the sea off Treasure Beach — a bucket-list stop for a cold drink with your feet in the water.',
    duration: 'Full Day',
    price: 90,
    category: 'day_tour',
    images: ['/images/tours/pelican-bar.jpg'], // representative stock photo, not verified as this exact location — swap when real photo available
    highlights: [
      'Boat ride out to the sandbar bar',
      'Swimming in open sea water',
      'Drinks and light food on-site',
      'Knowledgeable local boat captain',
      'Comfortable air-conditioned vehicle',
      'Flexible pickup times',
    ],
    available: true,
  },
  {
    id: '15',
    name: 'Bob Marley Museum (Kingston)',
    slug: 'bob-marley-museum-kingston',
    description: "Tour the Kingston home and studio of reggae legend Bob Marley, now preserved as a museum filled with memorabilia, photos, and the story of his life and music.",
    duration: 'Half Day',
    price: 60,
    category: 'day_tour',
    images: ['/images/tours/bob-marley-museum.jpg'],
    highlights: [
      'Guided museum tour',
      "Bob Marley's former home and studio",
      'Memorabilia and photo exhibits',
      'Knowledgeable local guide',
      'Comfortable air-conditioned vehicle',
      'Flexible pickup times',
    ],
    available: true,
  },
  {
    id: '4',
    name: 'Custom Attractions',
    slug: 'custom-attractions',
    description: 'Create your perfect day. You choose the places, we handle the rest. Our knowledgeable local drivers will take you anywhere in Jamaica — from hidden beaches to mountain villages to cultural landmarks.',
    duration: 'Flexible',
    price: 120,
    category: 'day_tour',
    images: [
      '/images/tours/custom-tours.jpg',
      '/images/tours/blue-hole.jpg',
      '/images/tours/wabbas-adventure.jpg',
    ],
    highlights: [
      'Fully customizable itinerary',
      'Expert local driver/guide',
      'Comfortable air-conditioned vehicle',
      'Multiple stops included',
      'Restaurant recommendations',
      'Flexible pickup times',
    ],
    available: true,
  },
  {
    id: '5',
    name: 'Airport Pickup',
    slug: 'airport-pickup',
    description: 'Reliable, comfortable airport pickup service anywhere in Jamaica. Start your vacation stress-free with a professional driver waiting for you at arrivals. We monitor your flight and adjust for any delays.',
    duration: 'As needed',
    price: 50,
    category: 'airport_transfer',
    images: [
      '/images/tours/airport.jpg',
      '/images/tours/custom-tours.jpg',
    ],
    highlights: [
      'Meet & greet at arrivals',
      'Flight monitoring service',
      'Air-conditioned vehicle',
      'Professional licensed driver',
      'Bottled water provided',
      'Door-to-door service',
    ],
    available: true,
  },
  {
    id: '6',
    name: 'Airport Drop-Off',
    slug: 'airport-dropoff',
    description: "Stress-free airport drop-off so you never miss a flight. Our punctual drivers will ensure you arrive at the airport with plenty of time. End your Jamaica vacation as smoothly as it began.",
    duration: 'As needed',
    price: 50,
    category: 'airport_transfer',
    images: [
      '/images/tours/airport.jpg',
      '/images/tours/custom-tours.jpg',
    ],
    highlights: [
      'Punctual pickup from hotel',
      'Real-time traffic monitoring',
      'Assistance with luggage',
      'Air-conditioned comfort',
      'Professional licensed driver',
      'Fixed price — no surprises',
    ],
    available: true,
  },
  {
    id: '16',
    name: 'Round Trip Transfers',
    slug: 'round-trip-transfers',
    description: 'Book your airport pickup and drop-off together. We track both flights and coordinate your accommodation pickup and return, so your whole trip is covered start to finish.',
    duration: 'As needed',
    price: 90,
    category: 'airport_transfer',
    images: [
      '/images/tours/airport.jpg',
      '/images/tours/custom-tours.jpg',
    ],
    highlights: [
      'Arrival and departure covered together',
      'Both flights monitored for delays',
      'Accommodation pickup and return included',
      'Air-conditioned comfort',
      'Professional licensed driver',
      'Fixed price — no surprises',
    ],
    available: true,
  },
  {
    id: '17',
    name: 'Charter',
    slug: 'charter',
    description: 'Private transportation from Point A to Point B, on your schedule. Choose a one-way or round trip journey to any destination you need — not a fixed tour or airport run, just you and where you need to be.',
    duration: 'As needed',
    price: 80,
    category: 'day_tour',
    images: [
      '/images/tours/custom-tours.jpg',
      '/images/tours/airport.jpg',
    ],
    highlights: [
      'Private point-to-point transportation',
      'One-way or round trip options',
      'Destination of your choice',
      'Professional licensed driver',
      'Comfortable air-conditioned vehicle',
      'Flexible pickup times',
    ],
    available: true,
  },
  {
    id: '7',
    name: 'Blue Hole Overnight Stay',
    slug: 'blue-hole-overnight',
    description: 'Spend a magical night at the Blue Hole Resort surrounded by nature. Wake up to birdsong, enjoy private access to the Blue Hole, and experience Jamaica\'s natural beauty at your own pace.',
    duration: '1-3 Nights',
    price: 200,
    category: 'overnight',
    images: [
      '/images/tours/overnight.jpg',
      '/images/tours/blue-hole.jpg',
      '/images/tours/wabbas-adventure.jpg',
    ],
    highlights: [
      'Private resort accommodation',
      'Exclusive Blue Hole access',
      'Breakfast included',
      'Evening bonfire and entertainment',
      'Nature trail walks',
      'Airport transfers available',
    ],
    available: true,
  },
]

export function getTourBySlug(slug: string): Tour | undefined {
  return TOURS.find((t) => t.slug === slug)
}

export function getToursByCategory(category: string): Tour[] {
  if (category === 'all') return TOURS
  return TOURS.filter((t) => t.category === category)
}
